### ISSUE TITLE
Promise rejection

### ISSUE THREAD

**Issue by michaelzangl** [zkoss/zkless-engine#4]
"zkless-engine": "0.1.22"

(node:19624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```js
		fs.readFile(path, 'utf-8', function (err, data) {
			if (err) {
				removeGenDir();
				throw err;
			}

			var data = helper.encodeDsp(data, theme, genDir);
			less.render(data).then(   // ← HERE HERE HERE HERE HERE HERE
				function (output) {
					if (callback)
						callback(helper.decodeDsp(output.css), path);
				},
				function (err) {
					removeGenDir();
					throw err; // ← Should be proper error handling
				}
			)
		});
```

Workaround:
To debug the real errors, set a breakpoint on the `throw err` line.

**Comment by cor3000** [comment]
as of now there's no plan to maintain the old version, and the new version should be used where possible.
